### ISSUE TITLE
Transaction table/chart enhancements

### ISSUE THREAD

**Issue by sfabara** [marscoin/martianrepublic#2]
- Better pending display of incoming transactions (live refresh) =>  possibly use socket connection to read in live tx data.
- Sort tx table as desc instead of asc
- Fix transaction chart for all users
![image](https://user-images.githubusercontent.com/32752276/176470108-3f596c79-2b3b-4c27-8bf9-a7ad34946c24.png)

**Comment by novalis78** [comment]
completely overhauled with Apexcharts.
![image](https://github.com/marscoin/martianrepublic/assets/190390/be0f26d1-be6c-4f71-a08f-3c21e38530a7)
